name: Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run canonical checks
        run: tools/check.sh
